export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const EXAMPLE_ACTION = 'EXAMPLE_ACTION'

export const ROUTE_SET_AUTHENTICATED = 'ROUTE_SET_AUTHENTICATED'
export const ROUTE_INIT_ACTION = 'ROUTE_INIT_ACTION'
export const ROUTE_PUSH_ACTION = 'ROUTE_PUSH_ACTION'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_SET_TOKEN = 'USER_SET_TOKEN'
export const USER_AUTH_BEGIN = 'USER_AUTH_BEGIN'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL'
export const USER_REGISTER = 'USER_REGISTER'
